"""add customized_images to cart_items

Revision ID: 6b6cc1cb2a00
Revises: e17df6a38a94
Create Date: 2025-09-06 18:30:42.783656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6cc1cb2a00'
down_revision: Union[str, Sequence[str], None] = 'e17df6a38a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('customized_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'customized_images')
    # ### end Alembic commands ###
