"""shipping table

Revision ID: e17df6a38a94
Revises: e8802b9fbad6
Create Date: 2025-08-28 18:06:33.982784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e17df6a38a94'
down_revision: Union[str, Sequence[str], None] = 'e8802b9fbad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_addresses', sa.Column('division', sa.String(length=255), nullable=False))
    op.add_column('shipping_addresses', sa.Column('district', sa.String(length=255), nullable=False))
    op.add_column('shipping_addresses', sa.Column('thana', sa.String(length=255), nullable=False))
    op.add_column('shipping_addresses', sa.Column('delivery_address', sa.String(length=255), nullable=False))
    op.drop_column('shipping_addresses', 'address_line')
    op.drop_column('shipping_addresses', 'state')
    op.drop_column('shipping_addresses', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_addresses', sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('shipping_addresses', sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('shipping_addresses', sa.Column('address_line', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_column('shipping_addresses', 'delivery_address')
    op.drop_column('shipping_addresses', 'thana')
    op.drop_column('shipping_addresses', 'district')
    op.drop_column('shipping_addresses', 'division')
    # ### end Alembic commands ###
